hydra:
  output_subdir: null
  run:
    dir: .


raw_data: 
  path: data/raw_data/dataset.tsv


clean_data:
  path: data/clean_data/currency_conversion.csv



outliers:
  upper_limit: 0.98
  lower_limit: 0.02
